### ISSUE TITLE
Ambigous call to overloaded function

### ISSUE THREAD

**Issue by arneves** [eyalz800/serializer#6]
Hi,

When I try to serialize a class that inherits from std::vector I get an "ambiguous call to the overloaded function" on serializer.h line 731.

Example:
class DOM : public vector<unique_ptr<GcDOMNode>>
{
friend zpp::serializer::access;
	template <typename Archive, typename Self>
	static void serialize(Archive & archive, Self & self)
	{
	}
}

Could you please shed some light in orvercomming this issue.

**Comment by eyalz800** [comment]
Well this is a nice edge case, stl container as public base class is not really recommended, as a workaround I suggest to use private inheritance and inherit the needed constructors/functions.

I shall try to see what the problem is but my guess it falls under two overloads - both the vector overload and the custom overload that I have for STL containers.
